source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!
platform :ios, '9.0'

target 'SBNetworking_Example' do
  pod 'SBNetworking', :path => '../'
  pod 'Eson', :git => 'https://github.com/schrockblock/eson'
  pod 'SwiftyJSON'

end

target 'SBNetworking_Tests' do
    use_frameworks!
    pod 'SBNetworking', :path => '../'
    pod 'Eson', :git => 'https://github.com/schrockblock/eson'
    
    pod 'Quick', '~> 1.0.0'
    pod 'Nimble', '~> 5.1.1'
    pod 'OHHTTPStubs/Swift'
end
